# -*- coding: utf-8 -*-
"""assignment 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCiY2mfw5dBRZpSL4WSsozTpRcsS-QoS
"""

import requests

api_key = '0bec91f5881b84fb9984bbf6082cedc9'


lat = '40.7128'  # Latitude of New York City
lon = '-74.0060'  # Longitude of New York City

# API endpoint URL
url = f"https://api.openweathermap.org/data/3.0/onecall?lat={lat}&lon={lon}&appid={api_key}"

# Make GET request to the OpenWeatherMap API
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Parse the JSON response
    data = response.json()

    with open('weather_data.json', 'w') as json_file:
        json.dump(data, json_file, indent=4)
    print("Weather data saved to weather_data.json")

    # Print some information about the weather
    print("Current Weather:", data['current']['weather'][0]['description'])
    print("Current Temperature (Celsius):", data['current']['temp'])
    print("Current Humidity:", data['current']['humidity'])
    print("Hourly Forecast:", data['hourly'])
    print("Daily Forecast:", data['daily'])
else:
    print("Failed to retrieve weather data from OpenWeatherMap API")
    print("Status code:", response.status_code)
    print("Response body:", response.text)

import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import requests

# Initialize the Dash app
app = dash.Dash(__name__)


api_key = '0bec91f5881b84fb9984bbf6082cedc9'

lat = '40.7128'  # Latitude of New York City
lon = '-74.0060'  # Longitude of New York City

# API endpoint URL
url = f"https://api.openweathermap.org/data/3.0/onecall?lat={lat}&lon={lon}&appid={api_key}"

# Make GET request to the OpenWeatherMap API
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Parse the JSON response
    data = response.json()
else:
    print("Failed to retrieve weather data from OpenWeatherMap API")
    print("Status code:", response.status_code)
    print("Response body:", response.text)
    data = None

# Define the layout of the dashboard
app.layout = html.Div([
    html.H1("Weather Dashboard"),
    html.Div(id="current-weather"),
    dcc.Interval(
        id='interval-component',
        interval=60*1000,  # Update every minute
        n_intervals=0
    )
])

# Define callback to update the content based on the data
@app.callback(
    Output("current-weather", "children"),
    [Input("interval-component", "n_intervals")]
)
def update_content(n):
    if data:
        # Current Weather
        current_weather = html.Div([
            html.H2("Current Weather"),
            html.Div("Description: " + data['current']['weather'][0]['description']),
            html.Div("Temperature (Celsius): " + str(data['current']['temp'])),
            html.Div("Humidity: " + str(data['current']['humidity']))
        ])
        return current_weather
    else:
        return "Error: Failed to retrieve weather data from OpenWeatherMap API"

# Run the Dash app
if __name__ == '__main__':
    app.run_server(debug=True)