"""assignment 1(a).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O7NXkpXtSc0H7kVbuRRUrglNm7kYYSMH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')
DF = pd.read_csv("/content/drive/MyDrive/datasheet/frailitydatasheet/data.csv")
DF

raw_data_path = '/content/drive/MyDrive/datasheet/frailitydatasheet/data.csv'
raw_data = pd.read_csv(raw_data_path)

cleaned_data = raw_data.dropna()

data = pd.DataFrame({
    'Height': [71.5, 69.4, 68.2, 67.8, 68.7, 69.8, 70.1, 67.9, 66.8],
    'Weight': [136, 153, 142, 144, 123, 141, 136, 112, 120],
    'Age': [19, 45, 22, 29, 50, 51, 23, 17, 39],
    'Grip strength': [31, 29, 28, 24, 26, 22, 20, 19, 31],
    'Frailty': ['N', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'N']
})
data['Frailty'] = data['Frailty'].map({'Y': 1, 'N': 0})
cleaned_data_path = '/content/drive/MyDrive/datasheet/frailitydatasheet/data/cleaned_data.csv'
data.to_csv(cleaned_data_path, index=False)
DF = pd.read_csv ('/content/drive/MyDrive/datasheet/frailitydatasheet/data/cleaned_data.csv')
DF

cleaned_data = pd.read_csv(cleaned_data_path)
descriptive_stats = cleaned_data.describe()
plt.figure(figsize=(10, 6))
plt.scatter(cleaned_data['Age'], cleaned_data['Grip strength'])
plt.xlabel('Age')
plt.ylabel('Grip strength')
plt.title('Scatter Plot of Age vs. Grip strength')
plt.grid(True)
plt.savefig('/content/drive/MyDrive/datasheet/frailitydatasheet/plots/scatter_plot.png')
plt.show()
correlation_coefficient = cleaned_data['Age'].corr(cleaned_data['Grip strength'])
analysis_results_path = '/content/drive/MyDrive/datasheet/frailitydatasheet/results/analysis_results.csv'
descriptive_stats.to_csv(analysis_results_path)

plt.figure(figsize=(10, 6))
plt.scatter(cleaned_data['Age'], cleaned_data['Frailty'])
plt.xlabel('Age')
plt.ylabel('Frailty')
plt.title('Scatter Plot of Age vs. Frailty')
plt.grid(True)
plt.savefig('/content/drive/MyDrive/datasheet/frailitydatasheet/plots/scatter_plot1.png')
plt.show()
correlation_coefficient = cleaned_data['Age'].corr(cleaned_data['Frailty'])
analysis_results_path = '/content/drive/MyDrive/datasheet/frailitydatasheet/results/analysis_results1.csv'
descriptive_stats.to_csv(analysis_results_path)
